# name= "Gourav"
# for i in name:
#     print(i)
#     if(i=="G"):
#         print("May be this is the first letter")

# colors = ['red',"blue","yellow","green"]
# for color in colors:
#     print(color)
#     for i in color:
#         print(i)    



for i in range(1,11):
    print(i,"Hello world")


for i in range(6):  #it will automatically convert (6) into (0,6)
    print(i) 

for i in range(1,12,5):#by default the 3rd paramater is set to 1 
    print("ok",i)    
# step parameter in range function     
# Purpose: It determines the increment value between each number in the sequence generated by the function.
# By default, if you don't specify it, the step is set to 1.


n = int(input("Enter the number: "))
print("The table of",n,"is: ")
for i in range(1,11):
    print(n,"x",i,"=",i*n)

